import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../global.css";

// import { ErrorProvider } from "./_context/ErrorContext";
// import { ErrorPopup } from "./_components/ErrorPopups";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function VendorRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <ErrorProvider>
          <ErrorPopup /> */}
        <aside>Vendor sidebar</aside>
        {children}
        {/* </ErrorProvider> */}
      </body>
    </html>
  );
}
